### ISSUE TITLE
APPCRASH on Exit

### ISSUE THREAD

**Issue by chris-** [LogikSim/LogikSim#52]
Sometimes when closing LogicSim a Windows APPCRASH message pops up. I haven't found a way to reproduce the issue consistently, it happens around 20 of the times.

Searching the internet such crashes are often related to thread issues...

**Comment by hacst** [comment]
Hm. Does it hang before that?

**Comment by chris-** [comment]
No, the Frame disappears as normal and after everything has disappeared the APPCRASH appears. Next time it occurs I will write down all the information.
